"""CRUD for the saves table (session persistence prep for long-form / detail-2).

Short-form gameplay still uses in-memory sessions in game/core/session.py.
This repository is ready for optional persistence and long-form save/load.
"""

from __future__ import annotations

import logging
from typing import Any

from game.db.supabase_client import get_supabase

logger = logging.getLogger(__name__)

_SAVE_COLUMNS = (
    "id, work_id, current_chapter_id, current_turn, stats, flags, chapter_summaries, "
    "hit_key_point_ids, hit_pitfall_ids, conversation_history, game_over, outcome, "
    "created_at, updated_at"
)


def _raise_from_response(action: str, response: Any) -> None:
    error = getattr(response, "error", None)
    if error:
        raise RuntimeError(f"Supabase {action} failed: {error}")


def create_save(payload: dict[str, Any]) -> dict[str, Any]:
    """Insert a save row. `id` is optional (uuid generated by DB if omitted)."""
    client = get_supabase()
    row = {
        "work_id": payload["work_id"],
        "current_chapter_id": payload["current_chapter_id"],
        "current_turn": payload.get("current_turn", 0),
        "stats": payload.get("stats", {}),
        "flags": payload.get("flags", {}),
        "chapter_summaries": payload.get("chapter_summaries", []),
        "hit_key_point_ids": payload.get("hit_key_point_ids", []),
        "hit_pitfall_ids": payload.get("hit_pitfall_ids", []),
        "conversation_history": payload.get("conversation_history", []),
        "game_over": payload.get("game_over", False),
        "outcome": payload.get("outcome"),
    }
    if payload.get("id"):
        row["id"] = payload["id"]

    response = client.table("saves").insert(row).execute()
    _raise_from_response("create save", response)
    data = (response.data or [None])[0]
    if not data:
        raise RuntimeError("Supabase create save returned no row")
    logger.info("[save_repository] created save %s for work %s", data["id"], data["work_id"])
    return data


def get_save(save_id: str) -> dict[str, Any] | None:
    client = get_supabase()
    response = (
        client.table("saves")
        .select(_SAVE_COLUMNS)
        .eq("id", save_id)
        .limit(1)
        .execute()
    )
    _raise_from_response(f"get save {save_id}", response)
    rows = response.data or []
    return rows[0] if rows else None


def update_save(save_id: str, updates: dict[str, Any]) -> dict[str, Any]:
    allowed = {
        "current_chapter_id",
        "current_turn",
        "stats",
        "flags",
        "chapter_summaries",
        "hit_key_point_ids",
        "hit_pitfall_ids",
        "conversation_history",
        "game_over",
        "outcome",
    }
    patch = {k: v for k, v in updates.items() if k in allowed}
    if not patch:
        existing = get_save(save_id)
        if not existing:
            raise FileNotFoundError(f"Save not found: {save_id}")
        return existing

    client = get_supabase()
    response = client.table("saves").update(patch).eq("id", save_id).execute()
    _raise_from_response(f"update save {save_id}", response)
    rows = response.data or []
    if not rows:
        raise FileNotFoundError(f"Save not found: {save_id}")
    return rows[0]


def delete_save(save_id: str) -> None:
    client = get_supabase()
    existing = get_save(save_id)
    if not existing:
        raise FileNotFoundError(f"Save not found: {save_id}")
    response = client.table("saves").delete().eq("id", save_id).execute()
    _raise_from_response(f"delete save {save_id}", response)
    logger.info("[save_repository] deleted save %s", save_id)


def list_saves_for_work(work_id: str) -> list[dict[str, Any]]:
    client = get_supabase()
    response = (
        client.table("saves")
        .select(_SAVE_COLUMNS)
        .eq("work_id", work_id)
        .order("updated_at", desc=True)
        .execute()
    )
    _raise_from_response(f"list saves for {work_id}", response)
    return list(response.data or [])
